package no.noroff.moviecharactersapi.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.Set;



/**
 The Character class represents a movie character entity.
 */
@Entity
@Getter
@Setter
public class Character {


    /**
     The ID of the character, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     The name of the character.
     */
    @Column(length=100, nullable = false)
    private String name;

    /**
     The alias of the character.
     */
    @Column(length=50)
    private String alias;


    /**
     The gender of the character.
     */
    @Column(length=10)
    private String gender;


    /**
     A picture of the character.
     */
    @Column
    private String picture;

    /**
     A set of movies that the character appears in.
     */
    @ManyToMany(mappedBy="characters")
    private Set<Movie> movies;



}