package no.noroff.moviecharactersapi.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.Set;


/**
 The Franchise class represents a movie franchise in the database.
 It contains information about the franchise's name and description,
 and a set of associated movies.
 */
@Entity
@Getter
@Setter
public class Franchise {

    /**
     The unique identifier for the franchise, generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     The name of the franchise, with a maximum length of 100 characters and required to be non-null.
     */
    @Column(length=100, nullable=false)
    private String name;


    /**
     The description of the franchise, with a maximum length of 300 characters.
     */
    @Column(length=300)
    private String description;


    /**
     A set of movies that are associated with the franchise.
     The relationship between franchise and movie is represented by the mappedBy attribute.
     */
    @OneToMany(mappedBy="franchise")
    private Set<Movie> movies;

}