package no.noroff.moviecharactersapi.models;


import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;


import java.util.Set;



/**
 The Movie class represents a movie.
 */
@Entity
@Getter
@Setter
public class Movie {


    /**
The id of the movie, generated by the database.
*/
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     The title of the movie.
     */


    @Column(length = 100, nullable = false)
    private String title;


    /**
     The genre of the movie.
     */
    @Column(length = 100)
    private String genre;

    /**
     The release year of the movie.
     */
    private int releaseYear;


    /**
     The director of the movie.
     */
    @Column(length = 50)
    private String director;


    /**
     The movie poster URL.
     */
    private String moviePoster;

    /**
     The trailer URL.
     */
    private String trailer;

    /**
     The franchise the movie belongs to.
     */
    @ManyToOne
    @JoinColumn
    private Franchise franchise;


    /**
     The set of characters appearing in the movie.
     */
    @ManyToMany
    private Set<Character> characters;

}
